bed_file: "CGX_SUREQUESTDX_213713.bed"

filter_thresholds:
  DP: 100
  GQ: 99

#######################
known_sites: "/home/ipseity-gnt-i9/ACMG/Mills_and_1000G_gold_standard.indels.b37.vcf"
ref: "/home/ipseity-gnt-i9/ACMG/GRCh37.p13.genome.fa"
bowtie_index: "/home/ipseity-gnt-i9/ACMG/human_37"
docker_data: "/home/ipseity-gnt-i9/ACMG/VEP_data"